---
title: "Assignments"
---


- Having problems: check our [Troubleshooting Guide](/assignments/troubleshooting.qmd)

## Tutorials

- [Tutorial Instructions](/assignments/tutorials.qmd)
- [Tutorial 1: Data Visualization](https://mblackwell.shinyapps.io/01-r-basics-data-viz/)
- [Tutorial 2: Data Wrangling](https://mblackwell.shinyapps.io/02-data-wrangling/)
- [Tutorial 3: Causality](https://mblackwell.shinyapps.io/03-causality/)
- [Tutorial 4: Summarizing Data](https://mblackwell.shinyapps.io/04-summarizing-data/)
- [Tutorial 5: Correlation and Tidying Data](https://mblackwell.shinyapps.io/05-correlation-tidying/)
- [Tutorial 6: Loops](https://mblackwell.shinyapps.io/06-loops/)
- [Tutorial 7: Regression and Sampling](https://mblackwell.shinyapps.io/07-regression/)
- [Tutorial 8: Bootstrap](https://mblackwell.shinyapps.io/08-bootstrap/)

## Problem Sets

- [Submission guide for problem sets](/assignments/problem-sets.html)
- [Problem set 0: Setting up R, RStudio, and GitHub](/assignments/00-problem-set.html)
- [Problem set 1: Data visualization](/assignments/01_hw_data_viz.qmd)
- [Problem set 2: Data wrangling](/assignments/02_hw_data_wrangling.qmd)
- [Problem set 3: Causality](/assignments/03_hw_causality.qmd)
- [Problem set 4: Summarizing data](/assignments/04_hw_summarizing.qmd)
- [Problem set 5: Regression](/assignments/05_hw_regression.qmd)
- [Problem set 6: Sampling](/assignments/06_hw_sampling.qmd)
- [Problem set 7: Bootstrap](/assignments/07_hw_bootstrap.qmd)
- [Problem set 8: Hypothesis testing](/assignments/08_hw_hyp_tests.qmd)
 


## Final Project 

- [Final project information](/assignments/final-project.html)
- [Final project milestone 1: Creating a repo](/assignments/distill.qmd)

