---
title: "Summarizing Relationships, Tidying and Joining Data"
date: 2023-10-09
---


## Readings 

- For summarizing relationships, see QSS 3.6 and MD 5.1.1. 
- For pivoting and tidy data, see MD Ch 4. 
- For more on joins, see the [chapter 20](https://r4ds.hadley.nz/joins.html) in R for Data Science.

## Data



- On Thursday, We will also use data from the `nycflights13` package that you can install with:
```{r}
#| eval: false
install.packages("nycflights13")
```




## Slides and Code

- Tuesday (10/10) lecture: Summarizing relationships and writing our own functions
  - [PDF of slides as I present them](/slides/11_bivariate.pdf)
  - [PDF of handout version of slides](/slides/11_bivariate_handout.pdf) (no incremental slides)
  - Code: [`lecture_11.Rmd`](/files/code/lecture_11.Rmd)

- Thursday (10/12) lecture: Pivoting longer, joining data.
  - [PDF of slides as I present them](/slides/12_tidy_joins.pdf)
  - [PDF of handout version of slides](/slides/12_tidy_joins_handout.pdf) (no incremental slides)
  - Code: [`lecture12.Rmd`](/files/code/lecture12.Rmd)

